version: '3'

services:

  django:
    build: .
    env_file:
      - .env
    command: bash -c "cd howareyoutwitter/ && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:10.9
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: