# Generated by Django 3.0.1 on 2020-01-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hashtag_tweet_tweethashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_id',
            field=models.CharField(max_length=300),
        ),
    ]
